# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Minutes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Minutes
	 # Use the following line to use App Center Analytics and Crashes.x
 pod 'AppCenter'

 # Use the following lines if you want to specify which service you want to use.
 pod 'AppCenter/Analytics'
 pod 'AppCenter/Crashes'
 pod 'AppCenter/Distribute'
  target 'MinutesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
